import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Iceberg,
  Michroma,
  Open_Sans,
} from "next/font/google";
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

const iceberg = Iceberg({
  variable: "--iceberg",
  weight: ["400"],
  subsets: ["latin"],
});

const michroma = Michroma({
  variable: "--michroma",
  weight: ["400"],
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--open-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${iceberg.variable} ${michroma.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
