import type { Metadata } from "next";
import {
  Iceberg,
  Michroma,
  Open_Sans,
  UnifrakturCook,
  Cinzel_Decorative,
  EB_Garamond,
} from "next/font/google";
import "./globals.css";

const iceberg = Iceberg({
  variable: "--iceberg",
  weight: ["400"],
  subsets: ["latin"],
});

const michroma = Michroma({
  variable: "--michroma",
  weight: ["400"],
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--open-sans",
  subsets: ["latin"],
});

const unifrakturCook = UnifrakturCook({
  variable: "--unifraktur",
  weight: ["700"],
  subsets: ["latin"],
});

const cinzelDecorative = Cinzel_Decorative({
  variable: "--cinzel",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--eb-garamond",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${iceberg.variable} ${michroma.variable} ${openSans.variable} ${unifrakturCook.variable} ${cinzelDecorative.variable} ${ebGaramond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
